version: "3"
services:
  search_proxy:
    container_name: vimcolorschemes_search_proxy
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      PORT: "3000"
      ELASTICSEARCH_HOST: "http://vimcolorschemes_elasticsearch:9200"
      WEBSITE_ORIGIN: "http://localhost:8000"
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    container_name: vimcolorschemes_elasticsearch
    environment:
      - cluster.name=vimcolorschemes
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

volumes:
  elasticsearch_data:
    driver: local
